
BLENDER="C:\Program Files\Blender Foundation\Blender 2.93\blender.exe"
DIST=../dist

all : \
    $(DIST)/lost-music.pnct \
    $(DIST)/lost-music.scene \

$(DIST)/lost-music.scene : lost-music.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "lost-music.blend:Main" "$(DIST)/lost-music.scene"

$(DIST)/lost-music.pnct : lost-music.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "lost-music.blend:Main" "$(DIST)/lost-music.pnct" 
